
kind: Service
apiVersion: v1
metadata:
  name: quarkus-microservice
  labels:
    app: quarkus-microservice
spec:
  type: NodePort
  selector:
    app: quarkus-microservice
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: quarkus-microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus-microservice
        version: v1
    spec:
      containers:
      - name: quarkus-microservice
        image: quarkus-microservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
